services:
  luna-chat:
    image: ghcr.io/shun-shobon/luna-chat:latest
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
    volumes:
      - ./data:/home/node/.luna
    init: true
    restart: unless-stopped
